import type { CatalogueItem } from "./types";

// SEED DATA ONLY. The live catalogue is in the database (tables `suppliers` and
// `products`) and is what the studio, quotes and orders use. Changing prices or
// products here does nothing to the running app until you re-seed:
//
//   npm run seed:catalogue
//
// Re-seeding overwrites database rows that share an id with an item below, so
// once suppliers manage their own products, treat the database as the source of
// truth and stop re-seeding. Items are listed in the order shown in the shop.
//
// Seed catalogue for the first region (Essex / Herts / London fringe). Décor,
// furniture, lighting, florals, signage and bars carry real AI-generated photos
// in /public/img/items. The newer categories (attire, stationery, cake & favours)
// ship with icon + swatch fallback cards until supplier photos are added.
const IMG = "/img/items";

export const CATALOGUE: CatalogueItem[] = [
  // ---------------------------------------------------------------- Backdrops
  {
    id: "bd-moongate",
    name: "Circular Moongate Arch",
    category: "backdrops",
    slot: "ceremony_backdrop",
    supplier: "Willow & Co Prop Hire",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 320,
    unit: "each",
    qtyRule: "fixed",
    styles: ["garden_romance", "modern_minimal", "classic_elegance"],
    icon: "⛩️",
    swatch: "#c9a0a0",
    image: `${IMG}/bd-moongate.png`,
    rating: 4.9,
    reviewCount: 38,
    leadTimeDays: 30,
    stock: "in_stock",
  },
  {
    id: "bd-rustic-arch",
    name: "Reclaimed Timber Arch",
    category: "backdrops",
    slot: "ceremony_backdrop",
    supplier: "Willow & Co Prop Hire",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 265,
    unit: "each",
    qtyRule: "fixed",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🪵",
    swatch: "#8a6f52",
    image: `${IMG}/bd-rustic-arch.png`,
    rating: 4.8,
    reviewCount: 52,
    leadTimeDays: 30,
    stock: "in_stock",
  },
  {
    id: "bd-plinth-pair",
    name: "Ivory Plinth Pair",
    category: "backdrops",
    slot: "ceremony_backdrop",
    supplier: "Mono Event Studio",
    supplierArea: "St Albans, Herts",
    unitPrice: 180,
    unit: "pair",
    qtyRule: "fixed",
    styles: ["modern_minimal", "classic_elegance"],
    icon: "🏛️",
    swatch: "#d8c7ad",
    image: `${IMG}/bd-plinth-pair.jpg`,
    rating: 4.7,
    reviewCount: 19,
    leadTimeDays: 21,
    stock: "low_stock",
  },

  // -------------------------------------------------------------- Florals
  {
    id: "fl-garden-romance",
    name: "Garden Romance Floral Package",
    category: "florals",
    slot: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 95,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["garden_romance", "classic_elegance"],
    icon: "💐",
    swatch: "#d9b7ad",
    image: `${IMG}/fl-garden-romance.png`,
    rating: 5.0,
    reviewCount: 73,
    leadTimeDays: 90,
    stock: "made_to_order",
    note: "Includes ceremony arrangements + top-table run, priced per table.",
  },
  {
    id: "fl-wildflower",
    name: "Wildflower Meadow Package",
    category: "florals",
    slot: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 78,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🌸",
    swatch: "#c9a0a0",
    image: `${IMG}/fl-wildflower.png`,
    rating: 4.9,
    reviewCount: 61,
    leadTimeDays: 90,
    stock: "made_to_order",
  },
  {
    id: "fl-sculptural",
    name: "Sculptural Stem Package",
    category: "florals",
    slot: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 70,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["modern_minimal"],
    icon: "🪷",
    swatch: "#8a9a82",
    image: `${IMG}/fl-sculptural.jpg`,
    rating: 4.7,
    reviewCount: 18,
    leadTimeDays: 90,
    stock: "made_to_order",
  },
  {
    id: "fl-bridal-bouquet",
    name: "Bridal Bouquet + Buttonholes",
    category: "florals",
    supplier: "Bloomwell Florals",
    supplierArea: "Ware, Herts",
    unitPrice: 180,
    unit: "set",
    qtyRule: "fixed",
    styles: ["garden_romance", "classic_elegance", "rustic_barn", "modern_minimal"],
    icon: "💮",
    swatch: "#d9b7ad",
    rating: 4.9,
    reviewCount: 44,
    leadTimeDays: 90,
    stock: "made_to_order",
    note: "Bridal bouquet plus five buttonholes for the wedding party.",
  },

  // -------------------------------------------------------------- Centrepieces
  {
    id: "cp-foliage-runner",
    name: "Foliage Table Runner",
    category: "centrepieces",
    slot: "centrepieces",
    supplier: "Fen & Fable Styling",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 48,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "garden_romance", "modern_minimal"],
    icon: "🌿",
    swatch: "#8a9a82",
    image: `${IMG}/cp-foliage-runner.png`,
    rating: 4.9,
    reviewCount: 64,
    leadTimeDays: 14,
    stock: "in_stock",
  },
  {
    id: "cp-candelabra",
    name: "Gold Candelabra + Blooms",
    category: "centrepieces",
    slot: "centrepieces",
    supplier: "Fen & Fable Styling",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 72,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🕯️",
    swatch: "#a67c52",
    image: `${IMG}/cp-candelabra.png`,
    rating: 4.8,
    reviewCount: 41,
    leadTimeDays: 14,
    stock: "in_stock",
  },
  {
    id: "cp-stem-vase",
    name: "Single-Stem Vase Trio",
    category: "centrepieces",
    slot: "centrepieces",
    supplier: "Mono Event Studio",
    supplierArea: "St Albans, Herts",
    unitPrice: 34,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["modern_minimal"],
    icon: "🌾",
    swatch: "#b0a99c",
    image: `${IMG}/cp-stem-vase.jpg`,
    rating: 4.6,
    reviewCount: 23,
    leadTimeDays: 14,
    stock: "in_stock",
  },

  // -------------------------------------------------------------- Furniture
  {
    id: "ch-crossback",
    name: "Oak Crossback Chair",
    category: "furniture",
    slot: "chairs",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 6.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["rustic_barn", "garden_romance", "classic_elegance"],
    icon: "🪑",
    swatch: "#8a6f52",
    image: `${IMG}/ch-crossback.png`,
    rating: 4.9,
    reviewCount: 88,
    leadTimeDays: 45,
    stock: "in_stock",
  },
  {
    id: "ch-chiavari",
    name: "Gold Chiavari Chair",
    category: "furniture",
    slot: "chairs",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 5.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🪑",
    swatch: "#a67c52",
    image: `${IMG}/ch-chiavari.png`,
    rating: 4.7,
    reviewCount: 71,
    leadTimeDays: 45,
    stock: "in_stock",
  },
  {
    id: "ch-bentwood",
    name: "Black Bentwood Chair",
    category: "furniture",
    slot: "chairs",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 5.0,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["modern_minimal"],
    icon: "🪑",
    swatch: "#2b2622",
    image: `${IMG}/ch-bentwood.jpg`,
    rating: 4.6,
    reviewCount: 34,
    leadTimeDays: 45,
    stock: "low_stock",
  },
  {
    id: "fn-round-table",
    name: "Round Banquet Table (seats 10)",
    category: "furniture",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 14,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["garden_romance", "classic_elegance", "rustic_barn", "modern_minimal"],
    icon: "⭕",
    swatch: "#b0a99c",
    rating: 4.8,
    reviewCount: 52,
    leadTimeDays: 45,
    stock: "in_stock",
  },
  {
    id: "fn-trestle-table",
    name: "Rustic Trestle Table",
    category: "furniture",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 18,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "modern_minimal"],
    icon: "🟫",
    swatch: "#8a6f52",
    rating: 4.7,
    reviewCount: 39,
    leadTimeDays: 45,
    stock: "in_stock",
  },

  // ---------------------------------------------------- Linen & tableware
  {
    id: "tl-linen-natural",
    name: "Natural Slub Linen + Napkins",
    category: "linen_tableware",
    slot: "tables_linen",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 28,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["rustic_barn", "modern_minimal", "garden_romance"],
    icon: "🍽️",
    swatch: "#efe7db",
    image: `${IMG}/tl-linen-natural.jpg`,
    rating: 4.8,
    reviewCount: 46,
    leadTimeDays: 21,
    stock: "in_stock",
  },
  {
    id: "tl-linen-ivory",
    name: "Ivory Damask Linen + Charger",
    category: "linen_tableware",
    slot: "tables_linen",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 39,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🍽️",
    swatch: "#f3ecdf",
    image: `${IMG}/tl-linen-ivory.jpg`,
    rating: 4.7,
    reviewCount: 29,
    leadTimeDays: 21,
    stock: "in_stock",
  },
  {
    id: "tw-napkin-linen",
    name: "Washed Linen Napkins (set of 10)",
    category: "linen_tableware",
    supplier: "Heirloom Linens",
    supplierArea: "Hertford, Herts",
    unitPrice: 15,
    unit: "per table",
    qtyRule: "per_table",
    styles: ["garden_romance", "rustic_barn", "modern_minimal", "classic_elegance"],
    icon: "🧻",
    swatch: "#e7ded0",
    rating: 4.8,
    reviewCount: 33,
    leadTimeDays: 14,
    stock: "in_stock",
  },
  {
    id: "tw-glassware",
    name: "Crystal Glassware Package",
    category: "linen_tableware",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 4.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["classic_elegance", "garden_romance", "modern_minimal"],
    icon: "🥂",
    swatch: "#d8c7ad",
    rating: 4.7,
    reviewCount: 41,
    leadTimeDays: 21,
    stock: "in_stock",
  },
  {
    id: "tw-cutlery-gold",
    name: "Brushed Gold Cutlery (per setting)",
    category: "linen_tableware",
    supplier: "County Furniture Hire",
    supplierArea: "Bishop's Stortford, Herts",
    unitPrice: 3.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["classic_elegance", "garden_romance", "modern_minimal"],
    icon: "🍴",
    swatch: "#a67c52",
    rating: 4.6,
    reviewCount: 27,
    leadTimeDays: 21,
    stock: "low_stock",
  },

  // -------------------------------------------------------------- Lighting
  {
    id: "lt-festoon",
    name: "Festoon Canopy Package",
    category: "lighting",
    slot: "lighting",
    supplier: "Lumen Wedding Lighting",
    supplierArea: "Brentwood, Essex",
    unitPrice: 540,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["rustic_barn", "garden_romance"],
    icon: "💡",
    swatch: "#d8c7ad",
    image: `${IMG}/lt-festoon.jpg`,
    rating: 4.9,
    reviewCount: 57,
    leadTimeDays: 60,
    stock: "in_stock",
  },
  {
    id: "lt-fairy",
    name: "Fairy-Light Backdrop Wall",
    category: "lighting",
    slot: "lighting",
    supplier: "Lumen Wedding Lighting",
    supplierArea: "Brentwood, Essex",
    unitPrice: 380,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["garden_romance", "classic_elegance", "rustic_barn"],
    icon: "✨",
    swatch: "#f3ecdf",
    image: `${IMG}/lt-fairy.jpg`,
    rating: 4.8,
    reviewCount: 43,
    leadTimeDays: 60,
    stock: "in_stock",
  },
  {
    id: "lt-uplight",
    name: "Architectural Uplighting (x10)",
    category: "lighting",
    slot: "lighting",
    supplier: "Lumen Wedding Lighting",
    supplierArea: "Brentwood, Essex",
    unitPrice: 300,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["modern_minimal", "classic_elegance"],
    icon: "🔦",
    swatch: "#b0a99c",
    image: `${IMG}/lt-uplight.jpg`,
    rating: 4.6,
    reviewCount: 22,
    leadTimeDays: 60,
    stock: "in_stock",
  },

  // -------------------------------------------------------------- Signage
  {
    id: "sg-mirror",
    name: "Gold-Framed Welcome Mirror",
    category: "signage",
    slot: "signage",
    supplier: "Willow & Co Prop Hire",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 85,
    unit: "each",
    qtyRule: "fixed",
    styles: ["classic_elegance", "garden_romance"],
    icon: "🪞",
    swatch: "#a67c52",
    image: `${IMG}/sg-mirror.jpg`,
    rating: 4.8,
    reviewCount: 27,
    leadTimeDays: 14,
    stock: "in_stock",
  },
  {
    id: "sg-neon",
    name: "Custom Neon Sign",
    category: "signage",
    slot: "signage",
    supplier: "Mono Event Studio",
    supplierArea: "St Albans, Herts",
    unitPrice: 140,
    unit: "each",
    qtyRule: "fixed",
    styles: ["modern_minimal", "garden_romance"],
    icon: "🔆",
    swatch: "#d9b7ad",
    image: `${IMG}/sg-neon.jpg`,
    rating: 4.7,
    reviewCount: 31,
    leadTimeDays: 30,
    stock: "made_to_order",
  },

  // -------------------------------------------------------------- Bar & drinks
  {
    id: "bar-horsebox",
    name: "Horsebox Prosecco Bar",
    category: "bar",
    slot: "bar",
    supplier: "The Tipple Co Mobile Bars",
    supplierArea: "Colchester, Essex",
    unitPrice: 950,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🍾",
    swatch: "#b98a6a",
    image: `${IMG}/bar-horsebox.png`,
    rating: 4.9,
    reviewCount: 49,
    leadTimeDays: 120,
    stock: "low_stock",
  },
  {
    id: "bar-copper",
    name: "Copper-Top Cocktail Bar",
    category: "bar",
    slot: "bar",
    supplier: "The Tipple Co Mobile Bars",
    supplierArea: "Colchester, Essex",
    unitPrice: 1150,
    unit: "package",
    qtyRule: "per_venue",
    styles: ["classic_elegance", "modern_minimal"],
    icon: "🍸",
    swatch: "#a67c52",
    image: `${IMG}/bar-copper.png`,
    rating: 4.8,
    reviewCount: 36,
    leadTimeDays: 120,
    stock: "in_stock",
  },

  // -------------------------------------------------------------- Attire
  {
    id: "at-bridal-gown",
    name: "Made-to-Measure Bridal Gown",
    category: "attire",
    supplier: "The Ivory Room",
    supplierArea: "St Albans, Herts",
    unitPrice: 1850,
    unit: "each",
    qtyRule: "fixed",
    styles: ["garden_romance", "classic_elegance", "modern_minimal", "rustic_barn"],
    icon: "👰",
    swatch: "#f3ecdf",
    rating: 5.0,
    reviewCount: 58,
    leadTimeDays: 180,
    stock: "made_to_order",
    note: "Includes two fittings. Final alterations six weeks before the day.",
  },
  {
    id: "at-groom-suit",
    name: "Three-Piece Groom Suit Hire",
    category: "attire",
    supplier: "Tailor & Fox",
    supplierArea: "Chelmsford, Essex",
    unitPrice: 160,
    unit: "each",
    qtyRule: "fixed",
    styles: ["classic_elegance", "modern_minimal", "garden_romance"],
    icon: "🤵",
    swatch: "#2b2622",
    rating: 4.8,
    reviewCount: 72,
    leadTimeDays: 60,
    stock: "in_stock",
  },
  {
    id: "at-bridesmaid",
    name: "Bridesmaid Dress",
    category: "attire",
    supplier: "The Ivory Room",
    supplierArea: "St Albans, Herts",
    unitPrice: 145,
    unit: "each",
    qtyRule: "fixed",
    styles: ["garden_romance", "classic_elegance", "modern_minimal", "rustic_barn"],
    icon: "👗",
    swatch: "#d9b7ad",
    rating: 4.7,
    reviewCount: 48,
    leadTimeDays: 90,
    stock: "made_to_order",
  },

  // -------------------------------------------------------------- Stationery
  {
    id: "st-invites",
    name: "Invitation Suite (per guest)",
    category: "stationery",
    supplier: "Press & Fold Studio",
    supplierArea: "Hertford, Herts",
    unitPrice: 4.5,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["garden_romance", "classic_elegance", "modern_minimal", "rustic_barn"],
    icon: "✉️",
    swatch: "#e7ded0",
    rating: 4.9,
    reviewCount: 64,
    leadTimeDays: 60,
    stock: "made_to_order",
    note: "Invitation, RSVP and details card with envelopes.",
  },
  {
    id: "st-placecards",
    name: "Calligraphy Place Cards",
    category: "stationery",
    supplier: "Press & Fold Studio",
    supplierArea: "Hertford, Herts",
    unitPrice: 2.0,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["garden_romance", "classic_elegance", "modern_minimal"],
    icon: "🏷️",
    swatch: "#d8c7ad",
    rating: 4.8,
    reviewCount: 37,
    leadTimeDays: 30,
    stock: "made_to_order",
  },
  {
    id: "st-tableplan",
    name: "Table Plan + Menu Cards",
    category: "stationery",
    supplier: "Press & Fold Studio",
    supplierArea: "Hertford, Herts",
    unitPrice: 165,
    unit: "set",
    qtyRule: "fixed",
    styles: ["garden_romance", "classic_elegance", "modern_minimal", "rustic_barn"],
    icon: "📜",
    swatch: "#efe7db",
    rating: 4.7,
    reviewCount: 25,
    leadTimeDays: 30,
    stock: "made_to_order",
  },

  // -------------------------------------------------------- Cake & favours
  {
    id: "ck-three-tier",
    name: "Three-Tier Wedding Cake",
    category: "cake_favours",
    supplier: "Sugar & Thyme",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 395,
    unit: "each",
    qtyRule: "fixed",
    styles: ["garden_romance", "classic_elegance"],
    icon: "🎂",
    swatch: "#f3ecdf",
    rating: 5.0,
    reviewCount: 51,
    leadTimeDays: 60,
    stock: "made_to_order",
    note: "Serves up to 100. Tasting box posted before you confirm.",
  },
  {
    id: "ck-naked-cake",
    name: "Semi-Naked Buttercream Cake",
    category: "cake_favours",
    supplier: "Sugar & Thyme",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 310,
    unit: "each",
    qtyRule: "fixed",
    styles: ["rustic_barn", "garden_romance"],
    icon: "🍰",
    swatch: "#e7ded0",
    rating: 4.9,
    reviewCount: 43,
    leadTimeDays: 60,
    stock: "made_to_order",
  },
  {
    id: "fv-favour-boxes",
    name: "Personalised Favour Boxes",
    category: "cake_favours",
    supplier: "Fen & Fable Styling",
    supplierArea: "Saffron Walden, Essex",
    unitPrice: 3.0,
    unit: "per guest",
    qtyRule: "per_guest",
    styles: ["garden_romance", "classic_elegance", "modern_minimal", "rustic_barn"],
    icon: "🎁",
    swatch: "#d9b7ad",
    rating: 4.6,
    reviewCount: 29,
    leadTimeDays: 30,
    stock: "in_stock",
  },
];
